# Generated by Django 5.1.7 on 2025-04-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(default='Documentation', max_length=80),
            preserve_default=False,
        ),
    ]
