# Generated by Django 5.1.7 on 2025-04-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_video_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Sci-Fi', 'Science Fiction'), ('Thriller', 'Thriller'), ('Documentary', 'Documentary'), ('Musical', 'Musical'), ('Western', 'Western'), ('Crime', 'Crime'), ('Biography', 'Biography'), ('Sports', 'Sports'), ('Historical', 'Historical')], max_length=80),
        ),
    ]
